### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by mansona** [kaliber5/ember-in-element-polyfill#57]
Howdy folks? 

Any chance we can get a 1.0 version of this? It seems to be used by loads of people but I think it would be better to get it into "proper semver" if at all possible 🤔 

Any thoughts?

**Comment by simonihmig** [comment]
Hey @mansona, my idea was to wait until the feature officially lands in Ember itself, as it's IMHO kinda weird to have a polyfill for a - again officially - non-existent feature. This peace of code here specifically makes me think it's not quite ready yet for 1.0: https://github.com/kaliber5/ember-in-element-polyfill/blob/master/index.js#L7

But happy to be persuaded otherwise! 😄

**Comment by mansona** [comment]
It looks like it might be coming in 3.18 🤔 but I've asked a clarifying question in https://github.com/emberjs/rfc-tracking/issues/25#issuecomment-599437794

**Comment by simonihmig** [comment]
Done! :tada:

**Comment by mansona** [comment]
yay! 🎉 thanks for putting so much work into this
